[package]
name = "dacalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "13.0.0"
pest = "2.7.6"
pest_derive = "2.7.6"
